### PR TITLE
Generaliation of status boxes and and error lists

### PR DESCRIPTION
**Pull request by pieter-edelman-nictiz**
Making reusable components in QML means that you have to create separate files for them. I put them in the root of the project, but it might be sensible to create a subfolder for this.

### CODE REVIEW

**Comment by vadi2** [comment]
I agree with the subfolder - should have `src/` for at least the project code (and what would you recommend for qml?). Let's do that in a separate PR.

**Comment by pieter-edelman-nictiz** [comment]
> 
> 
> Does scrolling the errors list still work for you?

It doesn't. I was just looking into it.
Unfortunately, QML can be a bit peculiar about sizing of elements and I'm not always able to follow how it's done.

**Comment by pieter-edelman-nictiz** [comment]
The latest update should make scrolling work again. I noticed that resizing doesn't work (not sure if it did before). I'll look into it.

**Comment by vadi2** [comment]
Yeah, I've discovered the same thing about sizing, it's why I had to do this:

https://github.com/vadi2/Hammer/blob/b5bcdc4bc84743cb9cf863ba7514609b57d3dcfa/Main.qml#L472-L480 - set scrollview to an explicit height even thought content was its only child.

**Comment by pieter-edelman-nictiz** [comment]
I have to admit I spent an embarrassingly long time figuring out where to put the `implcitWidth` and `implicitHeight` to get this working ;)

**Comment by vadi2** [comment]
Probably not as much as it took me to figure out to even use those properties in the first place :smile:

**Comment by vadi2** [comment]
Did you push the commit for that?

**Comment by pieter-edelman-nictiz** [comment]
Yeah, it's this one: https://github.com/vadi2/Hammer/commit/89d5b0b52f73cda4483cea5ffb7f72d13c8088f0
Just two changed lines. However, Travis has failed when uploading to transfer.sh. I'm not sure what happens now.

**Comment by vadi2** [comment]
`transfer.sh` is not super reliable :( but it's the best solution I know of for easily uploading a temporary file.

**Comment by vadi2** [comment]
Just kicking off the build again does the trick.

**Comment by vadi2** [comment]
The scrolling works (and you fixed the coloured gradient to fill the whole height - thanks!), but the messages aren't filling the width:

Selection_090

**Comment by pieter-edelman-nictiz** [comment]
Hmm ... did you resize the window?

**Comment by vadi2** [comment]
Yeah, I manually made it wider.

**Comment by pieter-edelman-nictiz** [comment]
Thanks 👍 
This latest fix should make resizing work again.

**Comment by vadi2** [comment]
Awesome, thanks! :grin:

**Pull request merged**
