### PR TITLE
Create selfcontained windows executable

### PR DESCRIPTION
**Pull request by vadi2**
#### Brief overview of PR changes/additions
This one doesn't require a previous installation of .NET Core.
#### Motivation for adding to Hammer
Makes it easier for new users, they can use Hammer out of the box.
#### Other info (issues closed, discussion etc)
`Hammer.exe` gets lost in the sea of DLL's :|

### CODE REVIEW

**Comment by vadi2** [comment]
Good to go.

**Comment by pieter-edelman-nictiz** [comment]
This is an area I know very little about. I can test the .exe however. Where can I find it?

**Comment by vadi2** [comment]
Ah sorry - click on the `appveyor` link in the checks and then on the `Artifacts` tab.

**Comment by pieter-edelman-nictiz** [comment]
Ah, did that. There are a lot of other files along the .exe, is that correct? I can succesfully run it on my computer.

**Comment by vadi2** [comment]
Yeah - that's the .NET Core framework, so the user doesn't have to install it by hand first.

The huge amount of files is unfortunate - but I'd like to make a convenient installer first so the user wouldn't need to see them, simply launch Hammer from the Start location once it's installed.

**Comment by vadi2** [comment]
The Qt Installer framework requires the person to use an actual wizard - kind of old fashioned. I tried the Windows App store the other day and it didn't work until I logged in - and it didn't log after either because "no devices were on my account".

I'm thinking of https://github.com/Squirrel/Squirrel.Windows - it's a pretty nice user experience, nothing to click on, just launch and off you go.

**Pull request merged**
